### ISSUE TITLE
[BUG] Can't remove a first created connection

### ISSUE THREAD

**Issue by texnicii** [cweijan/vscode-database-client#166]
- OS INFO :
4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux

I have a few MySQL and Postgres connections.
- when I try to remove the first global connection with MySQL it doesn't remove if I click "YES" (I think it is the connection I first made)
- when I try to edit it, it makes a copy with edited options
- other connections removing well

**Comment by ccfredbaum** [comment]
I have the same problem. Whenever I try to delete the first created connection (in a server that has been retired and no longer works) it asks me for confirmation and then does nothing. It never deletes the first connection. 

This is particularly bad as it causes endless timeout errors and sometimes crashes VSCode. I would love to know where the config that stores connections of the plugin is held to see if I can manually delete the connection

**Comment by plwalsh** [comment]
Just ran into this same problem myself. It happened when I was trying to convert my only connection from "global" to "workspace", since I now have workspaces that don't require access to that database. Upon saving the edit, it created a duplicate connection. I tried deleting both, but only the second connection would delete.

I then tried uninstalling the extension, but since I have so many different Remote-SSH workspaces, the extension is installed remotely on several different machines. And due to the connection initially being global, all of those remote machines seemingly have data stored somewhere for that connection. Like @ccfredbaum said, I would love to know where that data is stored, because it doesn't appear to be in any of the `settings.json` files. And now every time I reinstall the extension, the initial connection just comes right back.

**Comment by LostBeard** [comment]
Same initial problem here. After fighting to delete that entry, now if I have this extension enabled I eventually get an error stating that I have lost connection to the remote host shortly after clicking the MySQL extension button. The remote host is on a VM on the same machine. The "lost connection" is due to bad MySQL extension settings that cannot be removed through the extension itself (or even by uninstalling the extension.)

Unfortunately for me the only solution was uninstalling this extension (no more connection lost errors) and using the other ,more popular, MySQL extension. If this extension gets fixed I would love to try it again as I feel it is better than the alternative (when working.)

Surprisingly, uninstalling the extension does not remove the extensions settings. If I knew where the extension settings were saved I think deleting them would give a workaround to this problem.

**Comment by cweijan** [comment]
I have never been able to reproduce the problem, remove connection again and opening the developer tools will help me troubleshoot the problem .
![image](https://user-images.githubusercontent.com/27798227/118283356-dcdd0880-b501-11eb-8a10-a67b058401ff.png)

**Comment by LostBeard** [comment]
I have it up now. When I try to delete the top database entry (192.168.0.230) it doesn't delete because it can't connect to it (it is no longer reachable at that address.) 

![pic_3](https://user-images.githubusercontent.com/21184383/118290609-a02ef400-b4a4-11eb-95a3-a72b9ac28bb8.jpg)

**Comment by cweijan** [comment]
Hi, try version 3.8.2, I think it's fixed.

**Comment by diablur** [comment]
> Hi, try version 3.8.2, I think it's fixed.

i tried on version 3.8.2，but still couldn't delete the connection

**Comment by LostBeard** [comment]
Thank you for the quick update. I just tried it and I still cannot delete my trouble connection but it has moved from being the first in my connection list to being the last after the update.

When I click "Delete Conenction" in the right click menu and then click YES to confirm I am seeing the ETIMEOUT errors in developer tools and seeing the below error in the output window:
"2021-05-15 12:44:00 Ssh tunel occur error : Error: Timed out while waiting for handshake"

Somewhere I think it is trying to verify the connection is valid before it allows it to be deleted. The connection validation fails preventing the deletion.

**Comment by ccfredbaum** [comment]
I confirm my result is the same. I do not get a deletion, and I get an ERR time out.

**Comment by cweijan** [comment]
That's unfortunate, but the current code doesn't seem to have any problems.

**Comment by plwalsh** [comment]
Where is the connection stored? Can it be manually deleted?

**Comment by cweijan** [comment]
Version 3.9.0 has supported edit connection config, I think can fix this issue, try edit and save.
![image](https://user-images.githubusercontent.com/27798227/122857552-3b8c7200-d34b-11eb-98be-425e88910fb6.png)

**Comment by diablur** [comment]
> Version 3.9.0 has supported edit connection config, I think can fix this issue, try edit and save.
> ![image](https://user-images.githubusercontent.com/27798227/122857552-3b8c7200-d34b-11eb-98be-425e88910fb6.png)

resolve my problem

**Comment by LostBeard** [comment]
Thank you for adding the ability to edit the config for the addon manually. I would tell you if it fixed my inability to remove the problem entry but all (3) of my entries (including the problem 1) for that workspace have vanished. (Problem solved! lol) Not worried about that as they are easy enough to add. Thanks for the update!

**Comment by cweijan** [comment]
@LostBeard  Do you use ssh for remote development? In version 3.9.0, the configuration of ssh remote and ordinary environment is isolated .
