### ISSUE TITLE
[BUG] run sql doesn't understand $$ strings in postgres 

### ISSUE THREAD

**Issue by bjubes** [cweijan/vscode-database-client#235]
- OS INFO : Ubuntu 20.04.2
- VSCode: May 2021 (version 1.57)

The automatic 'run sql' buttons in the editor chop up dollar strings including functions. As a result I cannot run the command to create the function as the extension thinks in terminates at the first semicolon
![image](https://user-images.githubusercontent.com/7608114/124001479-acaed380-d9a2-11eb-80fc-290f544e2b65.png)

![image](https://user-images.githubusercontent.com/7608114/124001750-f13a6f00-d9a2-11eb-9eaf-5a885b055649.png)

**Comment by cweijan** [comment]
Currently passed; to identify sql, so this problem will exist for a long time, I suggest your select the statement then press `ctrl+enter`.

**Comment by zaiboot** [comment]
I had the same issue, just select all the text and run it by clicking `run selected text`

**Comment by cweijan** [comment]
After a lot of experimentation, because the syntax of stored procedures and functions is too flexible, it is impossible to support them.
If you often use stored procedures or functions, it is recommended to disable codelen.
![image](https://user-images.githubusercontent.com/27798227/144196926-e581872e-5392-4744-a646-a644749c548c.png)

**Comment by bestia-dev** [comment]
Because of the problem of parsing Postgres $$ string delimiters I avoid parsing in the VSCode Database Client extension.

For all my needs in Postgres, I use now the command `mysql.runSQLWithoutParse` instead of the default `mysql.runSQL`. I can select all or select a part of my sql code, and press `ctrl+enter`.

In VSCode-Preferences-Keyboard shortcut from the `command`: `mysql.runSQL` remove the keybinding `key`: `ctrl+enter`.

Then on `command`: `mysql.runSQLWithoutParse` add the same keybinding `key`: `ctrl+enter`,

and the When expression copied from the original shortcut:   `when`: `config.database-client.executeCursorSQLByShortcut && editorLangId =~ /sql|cql|postgres/ || config.database-client.executeCursorSQLByShortcut && resourceFilename =~ /.dbclient-js$/ || editorHasSelection && editorLangId =~ /sql|cql|postgres/ || editorHasSelection && resourceFilename =~ /.dbclient-js$/`.

**Comment by cweijan** [comment]
@bestia-dev I'm sorry this happens, does it only happen after the latest version? I'm working on fixing this, if you send me the SQL that causes the parsing failure, it will help me fix it.
