### ISSUE TITLE
[Feature] Do you have any plan to support cluster redis and es with http auth?

### ISSUE THREAD

**Issue by ottsion** [cweijan/vscode-database-client#242]
Thanks for the awesome job you did !!! so helpful to me

Here's the advice ask:
     - do you have any plan to support cluster redis?
     - do you have any plan to support create new k-v for redis? current just support change redis value as i know.
     - do you have any plan to support es with http auth?
    
thank you again~~~

**Comment by cweijan** [comment]
1 and 3 seems to be a good feature, which can be implemented in the future. 

Not support create key for redis because it have many key type, I suggest you open redis terminal then create key by redis command.
![image](https://user-images.githubusercontent.com/27798227/124530809-c9825580-de3f-11eb-95f6-c8b8e7228b6e.png)

**Comment by ottsion** [comment]
get it, thanks

**Comment by guoxbin** [comment]
cluster redis +1

**Comment by cweijan** [comment]
Redis cluster has supported at version 4.1.0 and es http auth has supported at version 3.9.8.
![image](https://user-images.githubusercontent.com/27798227/129466799-d1c7e3ff-f7bc-4a41-8b41-a9e66d83a6bc.png)
