### ISSUE TITLE
[Feature] Support UNIX socket connections

### ISSUE THREAD

**Issue by tomaszn** [cweijan/vscode-database-client#267]
I can't find the option to connect to a database via a unix socket.
In my case it is a MySQL database, and the socket is in /run/mysqld/mysqld.sock.

This should be also supported with "SSH Tunnel".

**Comment by cweijan** [comment]
I'm not plan to support unix socket.
And unix socket only allowed on same machine, through by SSH tunnel is unrealistic.

**Comment by mike-pt** [comment]
Bummer I was looking for an extension that allowed this (SQL tools does it but I prefer you're in general), If I can add 2 cents:

> unix socket only allowed on same machine

Not 100% accurate when using unix socket, say using mysql cmd line, you use the filesystem, that filesystem could be mounted in jails/containers, so several "hosts" (jails) can access it.. but that's a bit of a stretch

A big use case however can be Google Cloud SQL with  Cloud SQL Proxy.

The best way to connect to google cloud sql is using cloud_sql_proxy and although TCP ports can be used it makes mapping several databases very annoying, because they will all be local host and you essentially have to change ports, so this connection become hard to identify, and one could easely connect to the wrong env i.e.

Cloud sql proxy has built-in discovery so you can, with a simply command, create sockets for all the Dabatases in multiple google projects:

```
 cloud_sql_proxy -dir /tmp/cloud_sql_proxy -projects project1,project2                                                                                     [16:26:43]
2021/11/04 16:26:52 Rlimits for file descriptors set to {Current = 8500, Max = 9223372036854775807}
2021/11/04 16:26:56 Listening on /tmp/cloud_sql_proxy/project2:us-central1:env1-postgres-us-central1/.s.PGSQL.5432 for project2:us-central1:env1-postgres-us-central1
2021/11/04 16:26:56 Listening on /tmp/cloud_sql_proxy/project2:us-central1:env1-instance1 for project2:us-central1:env1-master
2021/11/04 16:26:56 Listening on /tmp/cloud_sql_proxy/project1:us-central1:env2-postgres-us-central1/.s.PGSQL.5432 for project1:us-central1:env2-postgres-us-central1
```

Now I can simply connect to socket `/tmp/cloud_sql_proxy/project2:us-central1:env1-instance1`

Supporting sockets is also much easier than certs.


How about not supporting it in the UI, but allowing us to specificity this in settings.json? (or config.json in this case) 

I.E. you would allow an optional "socketPath" param, if specified host/port are ignored would you possibly consider something like that?

**Comment by cweijan** [comment]
@mike-pt  Thank you for your detailed introduction, and I will try to support it.

**Comment by cweijan** [comment]
I add socket path option on view, but I don't like this connection, so I didn't test it.
![image](https://user-images.githubusercontent.com/27798227/141744514-a09caf13-1816-4e69-89ff-d1e1179e2605.png)

**Comment by mike-pt** [comment]
@cweijan thank you very much for this, this will make a huge difference for me and my colleagues daily :) 

Hopefully I can pay you back with some coffe(s) ;)
