### ISSUE TITLE
[BUG]SQL Code Len split SQL with an improper way

### ISSUE THREAD

**Issue by coolgate** [cweijan/vscode-database-client#274]
- OS INFO : Windows
- Database PostgreSQL
SQL Code Len is a useful feather, but when there is a 'not normal' SQL block, such as  CREATE FUNCTION... in plpgsql language, it split SQL with an improper way, so we cannot run the SQL by one click. screenshoot like:
![屏幕截图 2021-08-13 094926](https://user-images.githubusercontent.com/945930/129294248-6fa046f3-3f16-4d82-9f38-25464b76e82a.png)
To avoid this, my suggestion is use some special comment tag(such as "-- ### ---") to identify SQL block explicitly, not only depending on  “;”.

**Comment by cweijan** [comment]
After a lot of experimentation, because the syntax of stored procedures and functions is too flexible, it is impossible to support them.
If you often use stored procedures or functions, it is recommended to disable codelen.
![image](https://user-images.githubusercontent.com/27798227/144196926-e581872e-5392-4744-a646-a644749c548c.png)
